[target.thumbv7em-none-eabi]
runner = 'probe-rs run --chip Cortex-M4'
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "linker=thumbv7em-none-eabi",
]

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "info"