[target.thumbv7em-none-eabi]
runner = 'probe-rs run --chip STM32WB5MMGHx'
rustflags = [
#   "-C", "link-arg=-Tmemory.x",
#   "-C", "linker=thumbv7em-none-eabi",
]

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "info"